### ISSUE TITLE
TODO: Find Tier 4 Floor Masters

### ISSUE THREAD

**Issue by ayomeer** [ayomeer/DNF_Tower#5]
We only have one confirmed tier 4 combatant in Mek. Would be nice if we could get a couple more on board

**Comment by aesick** [comment]
Have to catch Rawbat, he is almost the same level. And its is Tier 5 (switched it).
Tier 4 is still missing, but i was thinking about Trancer. He played our last cup and seems good for that position, will ask him next time.

**Comment by teekaywhy** [comment]
Questions?

**Comment by aesick** [comment]
Trancer is on board, that means we have at least 1 floor master for each tier. We can close this one.

**Comment by aesick** [comment]
close
